### PR TITLE
Uninstall homebrew python before installing it again

### PR DESCRIPTION
**Pull request by tsparber**
`python` is already installed in travis, reinstalling it using just `brew install python` does not work.
As `pip` is removed beforehand travis fails consecutively as it can't be found.
See also this failed travis build: https://travis-ci.org/tsparber/pygame/jobs/175053207#L582

The function used was:
```
get_python_environment homebrew $PY_VERSION $(pwd)/_test_env 
```

The `--force` option does not make `brew` fail, even if it is not installed.

### CODE REVIEW

**Comment by matthew-brett** [comment]
Thanks - looks reasonable.   Will merge if it passes the travis tests, but these appear to be stalled.

**Comment by matthew-brett** [comment]
Oh dear - lots of unrelated test failures - I see of a build with your fix and some other fixes at https://travis-ci.org/MacPython/terryfy/builds/176900580

**Comment by matthew-brett** [comment]
I did some edits to get terryfy working on the new default xcode image, 7.4 - see #9.  It has your fix - would you mind taking a look?

**Comment by tsparber** [comment]
Thank you for integrating the fix (and all the other fixes) 👍

**Pull request closed without merging**
